# Creamos la imagen a partir de ubuntu versión 18.04
FROM ubuntu:18.04


# Damos información sobre la imagen que estamos creando
LABEL \
	version="1.0" \
	description="Ubuntu + Apache2 + virtual host" \
	creationDate="27/05/2023" \
	maintainer="Gorka Ruiz Alcalde <gorruiz@birt.eus>"


# Modo NONINTERACTIVE (solo en ejecucion)
ARG DEBIAN_FRONTEND=noninteractive


# Instalar o actualizar nano, apache y demás servicios
RUN \
	apt-get update && \ 
	apt-get install \
		nano \
		apache2 -y \
		proftpd \
		ssh \
		git -y && \
	apt-get clean


# Copiamos el index al directorio por defecto del servidor Web
COPY index1.html index2.html sitio1.conf sitio2.conf sitio1.key sitio1.cer /



# Creacion de directorios
# Mover archivos a contenedor
# Activar sitios web y ssl
RUN \
	mkdir var/www/html/sitioweb1 var/www/html/sitioweb2 /root/.ssh ./start_services && \
	mv index1.html /var/www/html/sitioweb1/index.html && \
	mv index2.html /var/www/html/sitioweb2/index.html && \
	mv sitioweb1.conf /etc/apache2/sites-available && \
	a2ensite sitioweb1 && \
	mv sitioweb2.conf /etc/apache2/sites-available && \
	a2ensite sitioweb2 && \
	mv sitio1.key /etc/ssl/private && \
	mv sitio1.cer /etc/ssl/certs && \
	a2enmod ssl


# Preconfiguracion servidores FTP, SSH
COPY ftp/gruiz.crt /etc/ssl/certs/
COPY ftp/gruiz1.key /etc/ssl/private/
COPY ftp/proftpd.conf /etc/proftpd
COPY ftp/tls.conf /etc/proftpd
COPY ssh/sshd_config /etc/ssh 
COPY init.sh ./start_services
